title: Menna Arafat
description: Personal Blog

url: https://Menna-Arafat.github.io
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed
future: true
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Posts
      url: /index.html
    - title: Research
      url: /research
    - title: About
      url: /about
    - title: Service
      url: /service
    - title: Contact
      url: /contact

social:
    github: Menna-Arafat
    twitter: Menna Arafat
    facebook: Menna Arafat
    email: mennaarafat.md@gmail.com
    linkedin: Menna Arafat
    youtube: Menna Arafat
  

google_analytics: "UA-58263416-1"

disqus:
    shortname: Menna Arafat
